### ISSUE TITLE
pdb nodes without an iri

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#127]
```MATCH (n) where not has(n.iri) RETURN count(n)```
returns 60 nodes 

```[FBrf0007734, FBrf0111704, FBrf0007735, FBrf0186027, FBrf0064802, FBim0000809, FBim0000810, FBim0000065, FBim0000064, FBrf0047185, FBrf0011558, FBim0000792, FBim0000950, FBrf0002274, FBrf0006003, FBim0000836, FBrf0012178, FBrf0098527, FBrf0178740, FBrf0088947, FBrf0015801, FBrf0007733, FBrf0007732, FBim0000051, FBim0000052, FBim0000680, FBim0000053, FBrf0013091, FBrf0008422, FBrf0002482, FBrf0005804, FBrf0021038, FBrf0029539, FBrf0009202, FBrf0037040, FBrf0006943, FBim0000788, FBim0000834, FBrf0020984, FBim0000833, FBim0000793, FBrf0014742, FBim0000802, FBim0000807, FBrf0003937, FBrf0002494, FBrf0006004, FBrf0010887, FBrf0191741, FBrf0089067, FBrf0087325, FBrf0025420, FBrf0041342, FBrf0007310, FBrf0002495, FBrf0029744, FBrf0002379, FBrf0002371, FBrf0000957]```

**Comment by dosumis** [comment]
All of these nodes are failing to be populated with details from FlyBase (iris are added at this point - see pub_tools.pubMove)

Two issues here:

(i) FBim (images) need to be treated separately - with different FlyBase query for details. 
(ii) FBrfs are failing because they lack a type in FlyBase.

To fix:

 - [ ] 1. Remove the images (& make a ticket for dealing with then separately).
 - [ ] 2. Make the type match into a `LEFT OUTER JOIN`
 - [ ] 3. Report problem to FlyBase (it would be good to get this fixed at source)
