### ISSUE TITLE
FBbt_00004660 claw synonym missing

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#138]
FBbt_00004660 in V2.

**Comment by dosumis** [comment]
Seems this is still broken:

`MATCH (p:pub)-[r]-(c:Class) where p.label = 'Unattributed' return r,c limit 5`

=> no rows !

I can't see any obvious problem with the addition script.  

Needs to be tested with debugger turned on.

**Comment by dosumis** [comment]
Update.  The problem is not with Unattributed

e.g. Claw works:

![image](https://user-images.githubusercontent.com/112839/74171659-d0933d00-4c26-11ea-9797-a58a8e277632.png)


It is with cases where we have a non-FBbt xref

e.g. 

mushroom body medial-vertical lobe arborizing neuron 2 (FBbt_00100242)

has 
MB-MVP2 attributed to FlyBrain_NDB:10467

Still needs to be fixed at Loading script level (I by me)

(N0te - we still have 2 Unattributed nodes - but this probably doesn't matter...?)
![image](https://user-images.githubusercontent.com/112839/74171502-94f87300-4c26-11ea-880b-87669493a004.png)
