### ISSUE TITLE
KB2Prod: Trying to create existing nodes

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#56]
Need to investigate why this is occurring as should simply find the existing node if exists (MATCH):

```
Processing chunk of 49 of 51 starting with: b'MATCH (s:VFB:Individual { iri : \'http://virtualflybrain.org/reports/VFBc_00045769\'}),  (o:Template:VFB:Individual { iri : \'http://virtualflybrain.org/reports/VFBc_00017894\'}) MERGE (s)-[r:in_register_with ]->(o) SET r = { iri : "http://purl.obolibrary.org/obo/RO_0002026" , typ : "Related" , label : "in register with" }'/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo4j_tools.py:111: UserWarning: {'code': 'Neo.ClientError.Schema.IndexAlreadyExists', 'message': "There already exists an index for label 'Individual' on property 'iri'. A constraint cannot be created until the index has been dropped."}
  warnings.warn(str(e))
/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo4j_tools.py:111: UserWarning: {'code': 'Neo.ClientError.Schema.ConstraintViolation', 'message': 'Node 128528 already exists with label pub and property "PMID"=[23541733]'}
  warnings.warn(str(e))
```

**Comment by dosumis** [comment]
I suspect minor issue with handful of pub nodes with PMIDs in KB.  Don't think it should be a blocker.  This is probably from an attempt to add a property (=> constraint violation) rather than a node.

**Comment by dosumis** [comment]
First line is just attempt to add existing constraint.  Can be ignored.

**Comment by dosumis** [comment]
Investigated a little further.  We need some agreement on standard IRIs to use for references.  I think that in discussion last year, we provisionally decided on PUBMED IRIs for this.   This is implemented in KB  but we didn't do anything to implement in pipeline to Prod.  I also discussed this issue with @matentzn  last week and we agreed that the best strategy was to settle on using FlyBase identifiers as primary iri (this covers many things that are not in pubmed such as books and v.old papers).  For the very few cases where a pub is not in FlyBase (typically for fly refs that are not only Drosophila), we should aim to persuade FlyBase to add.  We should also aim for our curators to submit any missing references to FlyBase so that we can get FBrf identifiers ahead of FlyBase releases.

Quick fix for this is:
- [ ]  Change iris for all pubs in KB to use FlyBase iri
- [ ]  Update pub loader scripts in pipeline to use FlyBase for iri.

**Comment by dosumis** [comment]
Should now be fixed.  Pubs now all use FlyBase iri. I don't *think* the pub loader scripts need changing.

**Comment by dosumis** [comment]
superseded by #51
