### ISSUE TITLE
Relationships on Channels

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#76]
Query about overlaps on Larval DS
It's understandable why the overlap is from the channel node but this isn't what we've done in the past (see flycircuit) and creates issues about the display of this data in a non 1-1 (Anat:Ind - Channel) situation as we don't currently don't differentiate.

Long term we need a strategy for displaying relationships on channels and or Anatomical Individual nodes.

Short term we either need to move the relationships up one level or add more complexity to the term info query. I propose changing the larval PDB to move relationships up until the term info call can be split out to handle all future situations and simplify the cypher.

**Comment by dosumis** [comment]
We have overlap on channels (to channels) AND anatomical individuals (to ontology classes) for both FlyCircuit and Truman lab collection in larva.  The overlap edge between channels is used to store voxel overlap figures. 

In the case of FlyCircuit we dynamically generate the overlap 'Type' assertions between anatomical individuals and ontology classes during OWL generation. In the case of David W's data I decided that the data looked clean enough to justify instantiating these directly in the KB. 

You may not see this clearly from looking at pdb.  That's because the OWL generation is badly broken for this dataset.  I haven't managed to spot any issues with representation in the KB. When I tried to run it locally I got a stack overflow from the Jython.

**Comment by Robbie1977** [comment]
@dosumis the larval site has been reloaded and AberOWL reloaded and your example query was working

**Comment by dosumis** [comment]
Which example query?  Can't seem to get metadata to display on larval site for any of the flip outs.  Might get a clearer picture of what's now going on by looking at the pdb version of for the larval data.  Can you point me to it (probably best to do via Slack).

**Comment by dosumis** [comment]
overlap queries for neurons not working for me on larval site.

Here's the overlap edges in KBW: 

![image](https://user-images.githubusercontent.com/112839/37615457-4b44b19a-2ba5-11e8-88d6-d22c08d755d7.png)

+ one example of one of these edges:  
![image](https://user-images.githubusercontent.com/112839/37615514-695ee1f0-2ba5-11e8-8b4c-aa329c965675.png)

**Comment by Robbie1977** [comment]
With most of the Neurons ending up as Thing in OWL the standard queries won't pick them up. Do we also need to add synaptic neuropil/ganglion queries to 'painted_domain'? as to hit the VNC sections?

**Comment by dosumis** [comment]
Above are all anat ind -> Class like everything else. Only change that's needed is to add a new gross- type 'expression pattern fragment' - which was used for cases where multiple cells depicted.  Need to think a bit about queries on these.

**Comment by dosumis** [comment]
Neurons don't end up as Thing in Scala build - this was just happening previously due to random failure of Jython code (recursion limits issue).
